apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if not .Values.mariadb.deployChart }}
  mariadb-password: {{ required "A valid Values.mariadb.db.password is required!"  .Values.mariadb.db.password | b64enc | quote }}
  {{- end }}
